### PR TITLE
Only transform exceptions if the request is expecting a JSON response.

### PR DESCRIPTION
**Pull request by computerfr33k**

### CODE REVIEW

**Comment by flugger** [comment]
Hey! Thanks for the pull request. This looks good, except that `expectsJson()` was introduced in Laravel 5.3, so it would be better if we do it the old way and use the same condition as the `exceptsJson` method. It would also be preferable if you moved the condition inside `transformExceptions()` so its easier to implement for those just using the trait.

**Comment by computerfr33k** [comment]
Oh, didn't realize the `expectsJson` was only introduced in 5.3. And, I'll make the change as you suggested.

**Comment by computerfr33k** [comment]
I'm now testing to make sure this works with lumen since it is using the `Request::capture()` to maintain compatibility for the method params.

**Comment by computerfr33k** [comment]
Seems like it's working to the best of my knowledge on lumen..

**Comment by flugger** [comment]
Looks good, but do we actually need to call `capture`? If so, perhaps its better to send the request object as a parameter?

**Comment by computerfr33k** [comment]
I thought about doing that, but passing it as a parameter would then require people who are using the trait to add the new request param which would be a breaking change. And this would be easiest to push as an update.

**Comment by flugger** [comment]
Yeah, you make a good point. Releasing this as it is now and can eventually make the change next time I release a major version. Thanks!

**Pull request merged**
