### PR TITLE
Fixed the problem with the only parameter functionality

### PR DESCRIPTION
**Pull request by tayfunkayahan**
See issue https://github.com/flugger/laravel-responder/issues/118

### CODE REVIEW

**Comment by flugger** [comment]
Thank you for explaining the issue in such detail in https://github.com/flugger/laravel-responder/issues/118. 

I've been tinkering a bit and there is indeed a bug as it should handle both arrays and strings. However, your solution creates new problems, which one of the unit tests picked up on.

We need to merge the fields with already parsed fields for the same entity, but it should also be explicitly casted to an array if it's a string. I believe this should work fine:

```php
$fieldsets[$key] = array_unique(array_merge(key_exists($key, $fieldsets) ? $fieldsets[$key] : [], $fields));
```

**Comment by tayfunkayahan** [comment]
Thanks for the quick reply, and sorry for my late response! I will look into it tomorrow, and edit my PR after I've tested it with your code. Keep you updated!

**Comment by tayfunkayahan** [comment]
I had this code already, I casted it in my project to quickly work with it because I needed it immediately but forgot to update it in the laravel-responder library folder (because I was experimenting)! 🤦‍♂️ Now I casted the field explicitly to an array, and by doing the short-handed if/else (instead of the coalescing operator (??)) block it is fixed.

Thanks for the reminder, it works like a charm! Hope to see it updated, so I can remove it from my vendor folder where it shouldn't be so I can update your package 👍 :) 

Besides this issue, good work on this nice library! Keep up the good work 💯 
@flugger

**Comment by flugger** [comment]
Thanks! I’ll tag a release soon :)

**Pull request merged**
