### PR TITLE
Relations with an includeXxx method won't be eager loaded anymore

### PR DESCRIPTION
**Pull request by IlCallo**
This opens up scenarios where there is a need to consider as a relation what in fact is just a method returning a Model or a Collection.

This resolves the original question of #84

### CODE REVIEW

**Comment by IlCallo** [comment]
It is possible to mock method_exists  using [php-mock](https://github.com/php-mock/php-mock) or with some trick using a different namespace for test suite, but I think that using a stub in this case is a more elegant solution

**Comment by flugger** [comment]
I see the stub has `'baz'` as a auto-loaded relation in the `$load` property. I also see the tests pass, but shouldn't `'baz'` also be eager loaded?

**Comment by flugger** [comment]
Nevermind, I see now that I missed the second `includeXxx` method in the Transformer

**Comment by flugger** [comment]
This only seems to handle root transformers though, what about nested relations that has transformers with `includeXxx` methods?

**Comment by IlCallo** [comment]
You're right I guess, I didn't noticed that aspect.
I don't really know where to put my hands to operate the filtering both on the top level relations and nested ones. Any hints?

Btw, while checking the code I found this which seems like an undocumented feature to define eager load query restriction on a per-Transformer basis

    if (method_exists($this, $method = 'load' . ucfirst($relation))) {
        $eagerLoads[$relation] = function ($query) use ($method) {
            return $this->$method($query);
        };
    }

**Comment by flugger** [comment]
I think we need to think along the lines of adding transformer mappings on the `$relations` property and then iterating over the transformers in the same way we extract default relations from `$load`. So basically, move the logic from the `TransformBuilder` class to the `Transformer` and make a recursive method in there.

About the `loadXxx` feature, it only worked for relations in `$load` which I believed would cause for confusion to the end user, so I let it out of the documentation until I could find a way to attach it to all relations. If we end up adding transformer mappings to the `$relations` property as well, I think that will also solve the problem for the `loadXxx` methods.

**Comment by IlCallo** [comment]
Do you have something already done about adding mappings also to $relations property?
Or shall I try to implement it myself?

**Comment by flugger** [comment]
Nope, haven't had time to dig into that yet. I'm approaching an important deadline at work and I've had to prioritize getting closer to that goal first. I will have more time at the end of the month though. With that being said, I would highly appreciate any efforts to solve it - I think most of the logic should already be in the `HasRelationships` trait, and it should just be generalized to work for all relations. But don't feel obliged in any way :)

**Comment by IlCallo** [comment]
I think that at this point the TODO list shall be:
- add mappings on $relation property as well;
- uniform the flow for $load and $relations where possible;
- fix #72 
- fix definitively #84 

In the meantime, I think a partial solution (this PR) is still better than no solution...

**Comment by IlCallo** [comment]
> But don't feel obliged in any way :)
Don't worry, if I'm working on this is because I need it too :P
I'll spend this week trying to fully understand the library code and resolving as many issues as possible (the ones I opened at least)

**Comment by flugger** [comment]
Thanks! And sure, we can merge this for now. Feel free to hit me up on Larachat (Laravel's Slack channel, username: flugg) if you have any questions regarding the codebase, I'd be happy to discuss.

**Pull request merged**
