### PR TITLE
Support for Laravel 6

### PR DESCRIPTION
**Pull request by emilsundberg**
Makes it possible to install this package on Laravel 6

### CODE REVIEW

**Comment by mwkohler** [comment]
This would be useful as we're using this package alot and we really want to upgrade to Laravel 6.0 but we also want to keep this package.

**Comment by flugger** [comment]
Thanks for the PR. Now that Laravel follows Semver, I suppose we shouldn't use `6.0.*`, but rather `^6.0.0`?

**Comment by mwkohler** [comment]
> Thanks for the PR. Now that Laravel follows Semver, I suppose we shouldn't use `6.0.*`, but rather `^6.0.0`?

I would like to make this change so it could merged now so I can upgrade, but I suppose I can't make changes to his PR.

**Comment by flugger** [comment]
Thanks @mwkohler. https://github.com/flugger/laravel-responder/pull/143 is merged, so closing this.

**Pull request closed without merging**
