### PR TITLE
Fix default parameter

### PR DESCRIPTION
**Pull request by cberio**
`explode()` second parameter must strings

Signed-off-by: cberio <jws8585@gmail.com>

### CODE REVIEW

**Comment by flugger** [comment]
Thank you for finding and fixing all the bugs 😄😘

**Comment by cberio** [comment]
@flugger sorry but it appends empty value and leads `RelationNotFoundException` exceptions 😢 
```php
[  
  0 => ''
]
```

**Comment by flugger** [comment]
Oh, I will look into it

**Comment by flugger** [comment]
Just pushed a fix and tagged `2.0.8`, did this solve all the issues?

**Comment by cberio** [comment]
yes it works now Thanks! 💯

**Comment by flugger** [comment]
Perfect! 🎉 Sorry about all the problems, working on writing integration tests to make sure all of these cases are tested properly in the future

**Pull request merged**
