### PR TITLE
Fix the example exception typo

### PR DESCRIPTION
**Pull request by nasyrov**
I would rather leave fix the parent class and change it to 'code' class variable...

### CODE REVIEW

**Comment by nasyrov** [comment]
@flugger what do you think?

**Comment by flugger** [comment]
I agree with the comments, definitely read better. But, the rename from `$code` to `$errorCode` would be a breaking change. Perhaps hold off on that for now?

**Comment by nasyrov** [comment]
@flugger cheers! please have a look at the parent class, it should be named like that otherwise it won't show the correct error code... I made this change cause it didn't work for me during the development...

**Comment by flugger** [comment]
Oh, I thought this was a change to the HttpException itself, but I see now this only changes the documentation. My bad! Looks all good then, nice catch, thanks :)

**Comment by nasyrov** [comment]
@flugger thanks!

**Pull request merged**
